### ISSUE TITLE
There is no difference between Urdu and Arabic characters in Unicode

### ISSUE THREAD

**Issue by Delta-Sigma** [urduhack/urdu-characters#10]
I came here with with very high hopes after seeing the report on propakistani.pk. This could be the start of something great and I admire your initiative. You are doing great work.

However, your claims about different 'Arabic' and 'Urdu' range, and the same in propakistani.pk is flawed. This range: 0600-06FF is different from what you call 'Arabic' range in the sense that this one contains characters that are used in normal text, while the second one are presentation forms. (Imagine trying to write out in a child's qaeda how many different shapes 'Bay' can be in. Or to force a certain form of letter somewhere) FB50-FBFF are presentation forms. Since this range is supposed to be used as standalone characters - it won't work with fonts that change shape/height/size of character based on context. This effect can be easily seen in any modern non-monospaced font but it is very clearly visible in Nastaleeq type fonts. The usual range for Arabic text (as you can verify from any Arabic source on the web) is 0600-06FF.

Unicode doesn't have separate code points for Urdu and Arabic. Urdu, Arabic, Persian, Sindhi, all occupy the same code points i.e. 0600-06FF.

I really want a separate range for languages written in nastaleeq scripts, and this got my hopes too high. This makes some sense when you see how much Urdu text is mixed with Arabic, and how many Urdu language users also use Arabic but won't understand Urdu in Naskh or Arabic in Nastaleeq. Separate code ranges would allow fonts that can use Naskh for Arabic and Nastaleeq for Urdu and Persian in a single font, but they don't exist. Such fonts won't require Apple to have region specific font settings (or however they do the nastaleeq bit, idk) and sites like medium.com can have a font that defaults to serif in English, naskh in Arabic and nastaleeq in Urdu/Persian/South Asian languages.

**Comment by akkefa** [comment]
Can you give a call? or skype call I want to discuss this thing in detail.

**Comment by Delta-Sigma** [comment]
Thanks you for your response. Sure I'd love to talk to you. I've seen your contact number on your website. Will call soon, IA. (By monday, I hope)

**Comment by naeem9** [comment]
I have made comparison table for difference between Unicode values of visually similar characters of Arabic and Urdu.
https://github.com/naeem9/UrduArabicCompare

**Comment by naeem9** [comment]
نسخ میں ایک حرف کی کل چار اشکال بنتی ہیں:
isolated
initial
medial
final
جب کہ نستعلیق میں ایسا نہیں ہے۔ یہاں ہر حرف کی چار سے زیادہ شکلیں بن سکتی ہیں
مثلا
نستعلیق میں ’’ب‘‘ کی 14 مختلف شکلیں اور نشستیں بنتی ہیں جو شان الحق حقی صاحب نے اپنے ایک شعر میں جمع کردی ہیں:
بل میں بلبل، بانس پہ بطخ، بوتل میں بیل، آب میں بندر
بمبئی میں سبحان اللہ مچھلی ڈوبی بیچ سمندر
![baa](https://user-images.githubusercontent.com/58520117/70994990-41b7e780-20f1-11ea-945e-5f294f90f827.PNG)

**Comment by akkefa** [comment]
> I have made comparison table for difference between Unicode values of visually similar characters of Arabic and Urdu.
> https://github.com/naeem9/UrduArabicCompare

I added your comparison  @urdutext

**Comment by akkefa** [comment]
> نسخ میں ایک حرف کی کل چار اشکال بنتی ہیں:
> isolated
> initial
> medial
> final
> جب کہ نستعلیق میں ایسا نہیں ہے۔ یہاں ہر حرف کی چار سے زیادہ شکلیں بن سکتی ہیں
> مثلا
> نستعلیق میں ’’ب‘‘ کی 14 مختلف شکلیں اور نشستیں بنتی ہیں جو شان الحق حقی صاحب نے اپنے ایک شعر میں جمع کردی ہیں:
> بل میں بلبل، بانس پہ بطخ، بوتل میں بیل، آب میں بندر
> بمبئی میں سبحان اللہ مچھلی ڈوبی بیچ سمندر
> ![baa](https://user-images.githubusercontent.com/58520117/70994990-41b7e780-20f1-11ea-945e-5f294f90f827.PNG)

@urdutext 
Can you explain more?

**Comment by urdutext** [comment]
> 
> 
> > نسخ میں ایک حرف کی کل چار اشکال بنتی ہیں:
> > isolated
> > initial
> > medial
> > final
> > جب کہ نستعلیق میں ایسا نہیں ہے۔ یہاں ہر حرف کی چار سے زیادہ شکلیں بن سکتی ہیں
> > مثلا
> > نستعلیق میں ’’ب‘‘ کی 14 مختلف شکلیں اور نشستیں بنتی ہیں جو شان الحق حقی صاحب نے اپنے ایک شعر میں جمع کردی ہیں:
> > بل میں بلبل، بانس پہ بطخ، بوتل میں بیل، آب میں بندر
> > بمبئی میں سبحان اللہ مچھلی ڈوبی بیچ سمندر
> > ![baa](https://user-images.githubusercontent.com/58520117/70994990-41b7e780-20f1-11ea-945e-5f294f90f827.PNG)
> 
> @urdutext
> Can you explain more?
It is for information only and not related to URDUHACK.
it is font related issue that for one character there are many forms and font maker use them for contextual reshaping of glyphs. 
for naskh font each character can have maximum four forms. 
for nastaleeq font each character can have more that four forms(shapes).
for "normalization" of text we replace (medical , initial , final) forms to isolated form.
other fomrs are used by font and layout engine. from keyboard we feed only isolated form. for some platform that do not support layout (reshaping) of RTL languages there is a hack that use contextual specific form instead of isolated form.

**Comment by urdutext** [comment]
![keyboardtoscreen](https://user-images.githubusercontent.com/58520117/83233036-89b25e80-a1a7-11ea-9566-81ffeeed49d5.png)

**Comment by akkefa** [comment]
@urdutext Whats is your number. I will call you.
