### ISSUE TITLE
Verification required that we are using correct Urdu characters|unicode points

### ISSUE THREAD

**Issue by akkefa** [urduhack/urdu-characters#11]
We need verification for different resources that we are using correct Urdu Unicode points. 

**Currently, We are using the code points provided by the Unicode organization.**
[https://www.unicode.org/cldr/charts/34/collation/ur.html](https://www.unicode.org/cldr/charts/34/collation/ur.html)

**Comment by iam-mhaseeb** [comment]
If we are using code points provided by Unicode then is there any way we can make sure they are solid?

**Comment by akkefa** [comment]
Just to make sure we are using correct Unicode point for Urdu character by some Pakistan research institutes or Professor. @iam-mhaseeb

**Comment by akkefa** [comment]
@mirfan899 

We need verification for different resources that we are using correct Urdu Unicode points.

Currently, We are using the code points provided by the Unicode organization.
https://www.unicode.org/cldr/charts/34/collation/ur.html

**Comment by mirfan899** [comment]
Code points are correct.
