### ISSUE TITLE
Verification required that Urdu, Arabic and other languages are using same unicode code points. 

### ISSUE THREAD

**Issue by akkefa** [urduhack/urdu-characters#28]
### Need to verify this statement.

Unicode doesn't have separate code points for Urdu and Arabic. Urdu, Arabic, Persian, Sindhi, all occupy the same code points i.e. **0600-06FF.**

**Comment by mirfan899** [comment]
Farsi, Arabic Unicode range is provided as follows:

https://en.wikipedia.org/wiki/Persian_alphabet
https://unicodemap.org/range/12/Arabic/
https://unicode.org/charts/PDF/U0600.pdf
https://en.wikipedia.org/wiki/Arabic_script

After going through every resource, I found out that Arabic is a superset of Urdu, Persian, and Sindhi.

**Comment by akkefa** [comment]
Ok. I think we are now 100% clear.

**Comment by urdutext** [comment]
یونیکوڈ چارٹ میں ایک حرف کی مختلف یونیکوڈ ویلیوز ہیں۔
اگر آپ یہ معلوم کرنا چاہتے ہوں کہ اردو زبان کے لیے استعمال ہونے والے حروف کون کون سے ہیں اور ان کی یونیکوڈ ویلیوز کیا ہے تو اس کا آسان طریقہ یہ ہے کہ اردو کے سٹینڈرڈ کی بورڈ کی مدد سے تمام حروف کو ورڈ میں لکھ لیں
اس کے بعد ہر حرف کے بعد آلٹ ایکس دبانے سے اس حرف کی یونیکوڈ ویلیو مل جائے گی۔
لکھتے ہوئے ہر حرف آئسلویٹنڈ فارم میں لکھا جاتا ہے اور کی بورڈ سے تمام حروف کی آئسولییٹڈ فارم کی یونیکوڈ ویلیو ہی دی جاتی ہے۔ 
جب کہ لے آوٹ انجن
 contextual reshaping 
کے لیے ابتدائی ، درمیانی اور فائنل فارم استعمال کرتے ہیں۔ 
اس لیے نارملائزئشن کے پراسیس میں اگر ٹیکسٹ میں ابتدائی درمیانی اور فائنل فارم کی یونیکوڈ ویلیوز ہوں تو انہیں آئسولیٹیڈ فارم میں تبدیل کر دیا جاتا ہے کیوں کہ کی بورڈ سے ہمیشہ آئیسولیٹنڈ فارم ان پٹ کی جاتی ہے اور تمام اردو ٹیکسٹ اس میں ہی لکھا جاتا ہے۔
اس کے بعد یہ فانٹ اور لے آوٹ انجن کی سائنس ہوتی ہے کہ اشکال کو سیاق و سباق کے حوالے سے اخذ کیا جاتا ہے۔

جن سسٹمز میں رائٹ ٹو لیفٹ زبان کی لے آوٹ اور سیاق و سباق کے لحاظ سے ری شیپنگ کی صلاحیت نہیں ہوتی وہاں ایک جگاڑ یہ بنا لیا جاتا ہے کہ ہر حرف کی اکیلی شکل یا آسولیٹیڈ فارم کے بجائے
context
کے مطابق حرف کی بننے والی شکل کی یونیکوڈ ویلیو لے آوٹ انجن کو فراہم کی جاتی ہیں اور اس طرح درست ڈسپلے ممکن ہوتا ہے۔
لیکن سرچ کرتے ہوئے اس طرح کے متن کی تلاش مشکل ہوتی ہے۔
لہذا نارملائزیشن کے عمل میں یہ ضروری ہوتا ہے کہ حرف کی ابتدائی ، وسطی اور آخری شکل کو آسولیٹیڈ فارم سے تبدیل کر دیا جائے۔
